# Generated by Django 3.0 on 2019-12-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
